apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjob-deployment.fullname" . }}
  labels:
    {{- include "cronjob-deployment.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cron.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "cronjob-deployment.selectorLabels" . | nindent 12 }}
            {{- with .Values.cron.podLabels }}
             {{- toYaml . | nindent 12 }}
             {{- end }}
           {{- with .Values.cron.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "cronjob-deployment.serviceAccountName" . }}
          restartPolicy: {{ .Values.cron.restartPolicy }}
          {{- with .Values.image.pullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            - name: intention-config
              configMap:
                name: {{ include "cronjob-deployment.fullname" . }}-intention
          containers:
            - name: {{ include "cronjob-deployment.name" . }}
              image: "{{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: intention-config
                  mountPath: /broker/config
              env:
                - name: VAULT_ADDR
                  value: {{ .Values.global.vaultAddress | quote }}
                - name: BROKER_ADDR
                  value: {{ .Values.global.brokerAddress | quote }}
                - name: BROKER_JWT
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.sourceSecret.name }}
                      key: {{ .Values.sourceSecret.brokerTokenKey }}
                - name: VAULT_ROLE_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.sourceSecret.name }}
                      key: {{ .Values.sourceSecret.vaultRoleIdKey }}
                - name: INTENTION_EVENT_URL
                  value: {{ .Values.intention.event.url | quote }}
                - name: INTENTION_ENVIRONMENT
                  value: {{ .Values.intention.service.environment | quote }}
                - name: OPENSHIFT_SECRET_NAME
                  value: {{ .Values.targetSecret.name | quote }}
                - name: OPENSHIFT_TOKEN_KEY
                  value: {{ .Values.targetSecret.brokerTokenKey | quote }}
                - name: OPENSHIFT_ROLE_KEY
                  value: {{ .Values.targetSecret.vaultRoleIdKey | quote }}
                - name: OPENSHIFT_SECRET_ID_KEY
                  value: {{ .Values.targetSecret.vaultSecretIdKey | quote }}
                - name: CREDENTIAL_SYNC_ENABLED
                  value: {{ .Values.credentialSync.enabled | quote }}
                - name: VAULT_SECRET_PATH
                  value: {{ .Values.credentialSync.vaultPath | quote }}
                - name: OPENSHIFT_SERVICE_SECRET_NAME
                  value: {{ .Values.credentialSync.targetSecretName | quote }}
              resources:
                 {{- toYaml .Values.cron.resources | nindent 16 }}