{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cronjob-deployment.fullname" . }}-egress
  labels:
    {{- include "cronjob-deployment.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cronjob-deployment.selectorLabels" . | nindent 6 }}
  egress:
    {{- range .Values.networkPolicy.egress }}
    - to:
      {{- if .cidr }}
      - ipBlock:
          cidr: {{ .cidr }}
      {{- else if .podSelector }}
      - podSelector:
          matchLabels:
            {{- toYaml .podSelector.matchLabels | nindent 12 }}
      {{- end }}
      {{- if .ports }}
      ports:
        {{- toYaml .ports | nindent 8 }}
      {{- end }}
    {{- end }}
  policyTypes:
    - Egress
{{- end }}
