{{- if and .Values.token.create .Values.serviceAccount.create }}
# Long-lived service account token.
#
# NR Broker therefore authenticates to the Kubernetes API by reading this
# long-lived token from the Secret below. Copy the `token` value into the
# `serviceAccountToken` field of the Vault `nr-broker-sync` configuration.
#
# The `kubernetes.io/service-account.name` annotation instructs the API server to
# mint a token for the referenced service account.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knox-tools-sync.tokenSecretName" . }}
  labels:
     {{- include "knox-tools-sync.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "knox-tools-sync.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
