global:
  name: "knox-provision"
  vaultAddress: "https://knox.io.nrs.gov.bc.ca"
  brokerAddress: "https://broker.io.nrs.gov.bc.ca"

image:
  registry: "artifacts.developer.gov.bc.ca/github-docker-remote/"
  repository: "bcgov/nr-broker-credential-injection/intention-provision-secret"
  tag: "v3.0.2"
  pullPolicy: IfNotPresent
  pullSecrets: []

cron:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  backoffLimit: 1
  restartPolicy: OnFailure
  activeDeadlineSeconds: 3600 # 1 hour maximum execution time
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
  podAnnotations: {}
  podLabels: {}
  resources: {}

sourceSecret:
  name: "service-approle-env-secret"
  brokerTokenKey: "token"
  vaultRoleIdKey: "role_id"

targetSecret:
  name: "service-approle-env-secret"
  brokerTokenKey: "token"
  vaultRoleIdKey: "role_id"
  vaultSecretIdKey: "secret_id"

intention:
  event:
    provider: "provision-secret-cronjob"
    reason: "Scheduled secret refresh"
    url: "https://console.apps.silver.devops.gov.bc.ca/"
    transient: true
  action:
    name: "package-provision"
    id: "provision"
    provision:
      - "approle/secret-id"
  service:
    name: "nodejs-sample"
    project: "oscar-example"
    environment: "development"
  user:
    name: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

networkPolicy:
  create: false
  # egress: A list of egress rules, each with `cidr` and optional `ports`.
  # Example:
  #   egress:
  #     - cidr: 10.0.0.0/24
  #       ports:
  #         - protocol: TCP
  #           port: 443
  egress: []

secretIdConfig:
  vaultRoleName: "project_service_environment"
  # The number of seconds to delay the destruction of the old secret_id after a new one is created.
  # This is useful to avoid race conditions where the old secret_id is destroyed before the new one is used.
  # Set to 0 to disable the delay.  
  expireDelaySeconds: 10

credentialSync:
  enabled: true
  vaultPath: "apps/data/env/project/service/fullenvironment"
  targetSecretName: "service-env-secret"